### ISSUE TITLE
Point redemptions shown that are not yet active

### ISSUE THREAD

**Issue by j-dogcoder** [FiniteSingularity/tau#13]

**Comment by FiniteSingularity** [comment]
Point redemption test modal in dashboard shows all point redemptions, even those that are inactive.  To fix:
1. Add checkbox to point redemption test modal to toggle only-active.
2. If only-active is checked, filter out non-active custom point redemptions from list, and rebuild select element.
This will allow the user to hide or show non-active custom point redemptions for testing.
