### ISSUE TITLE
[BUG] follows not registering as events

### ISSUE THREAD

**Issue by matthewbrandt** [FiniteSingularity/tau#136]
**Describe the bug**
When a channel receives a follow, there is no event being received in TAU.

**To Reproduce**
1. Auth TAU for channel.follow permission
2. Click the follow button on the Twitch profile (using another account that isn't following currently)
3. See nothing appear in TAU

**Expected behavior**
A channel-follow event should be registered in TAU.

**Screenshots**
n/a

**Deployment:**
Deployed on Railway. Forked repository is fully up to date with TAU/main.

**Additional context**
Test follows work fine. I have a channel goal for follows and that one is updating too. So it's literally the channel.follow endpoint causing some kind of issue. Too deep in there for me to figure out, but i see that some stuff is required for the v2 that might not have been for v1. 
Was updated in September with this PR: https://github.com/Team-TAU/tau/commit/2d1c3cb0eecca531ba42664c751e1903fd6f8cf6

**Comment by matthewbrandt** [comment]
@cgsdev0 do you have any idea why your PR might not be working? I tried debugging more but am lost :/

**Comment by cgsdev0** [comment]
i had to like, reset all the webhooks and re-register them in the TAU dashboard i think

**Comment by matthewbrandt** [comment]
@cgsdev0 oh i see! in the TAU webhooks monitor I don't even know how to reset these, as clicking these 3 buttons on the bottom doesn't change anything. is there a guide somewhere on this?
![Screenshot 2023-11-11 at 00 02 50](https://github.com/Team-TAU/tau/assets/67697593/b4661462-c76d-4297-8af7-8d675e24295b)

**Comment by cgsdev0** [comment]
ok i thiiink i just toggled the channel.follow one on and off a bunch of times and clicked the update button a bunch

i really don't remember :S

**Comment by matthewbrandt** [comment]
@cgsdev0 you were right. I forcefully _click around_ in my local TAU instance and then pushed it to my server-hosted instance on Railway and it *magically* started working again 🎉 I'll go ahead and close out this ticket, as it just seems to be an initialisation problem...
