### ISSUE TITLE
the test events for subscriptions are different from actual subscription events coming from twitch

### ISSUE THREAD

**Issue by rexroof** [FiniteSingularity/tau#29]
Triggering a test event in the web ui generates a different json object than an actual sub event from twitch.

examples:

Actual event from twitch:

```
{
  "id": "7dc9cbef-86d7-419b-ad10-8f2eecb7529d",
  "event_id": null,
  "event_type": "subscribe",
  "event_source": "PubSub",
  "event_data": {
    "topic": "channel-subscribe-events-v1.503715992",
    "message": {
      "benefit_end_month": 0,
      "user_name": "nperry0",
      "display_name": "nperry0",
      "channel_name": "rexroof",
      "user_id": "33002146",
      "channel_id": "503715992",
      "time": "2021-05-07T11:24:37.152109459Z",
      "sub_message": {
        "message": "does this cover the postage?",
        "emotes": null
      },
      "sub_plan": "1000",
      "sub_plan_name": "Channel Subscription (rexroof)",
      "months": 0,
      "cumulative_months": 2,
      "context": "resub",
      "is_gift": false,
      "multi_month_duration": 0
    }
  },
  "created": "2021-05-07T11:24:37+0000",
  "origin": "twitch"
}
```

a similar test event triggered via the web UI:

```
{
  "id": "2b4b6111-eac7-4190-8d8b-d7beecc04ca7",
  "event_id": "3395a76c-bc0f-4b35-a0ee-ac7a7bdf9f06",
  "event_type": "subscribe",
  "event_source": "TestCall",
  "event_data": {
    "type": "MESSAGE",
    "data": {
      "topic": "channel-subscribe-events-v1.44322889",
      "message": {
        "user_name": "nperry0",
        "display_name": "nperry0",
        "channel_name": "rexroof",
        "user_id": "33002146",
        "channel_id": "503715992",
        "time": "2021-05-07T11:50:12.652Z",
        "sub_plan": "1000",
        "sub_plan_name": "Channel Subscription",
        "cumulative_months": "2",
        "streak_months": "",
        "context": "resub",
        "is_gift": false,
        "sub_message": {
          "message": "does this cover the postage?",
          "emotes": []
        }
      }
    }
  },
  "created": "2021-05-07T11:50:12.665233+00:00",
  "origin": "test"
}
```

there are some different data types in there, and the information coming through is in different spots.

**Comment by FiniteSingularity** [comment]
Thanks for catching that @rexroof, and for the detailed response of an actual sub.  I'll take a look this afternoon, and get that fixed.

**Comment by FiniteSingularity** [comment]
Ok, looking at the full message structure- the Test data is actually closer to the raw message that is received by the PubSub listener:

```
{
  "type": "MESSAGE",
  "data": {
    "topic": "channel-subscribe-events-v1.503715992",
    "message": {
      "user_name": "nperry0",
      "display_name": "nperry0",
      // etc..
    }
  }
}
```

When I was re-doing the subscription message a couple weeks back, I apparently changed things to only grab the raw `data` field rather than the entire message.  I am going to go back to putting the entire message structure back in `event_data`.  The reason behind this- I'd like the `event_data` field to be the same data structure you'd receive from a native call of the API.  Unfortunately, @rexroof this will be a bit of a breaking change, if your bot was already properly grabbing the real subscribe events.  Apologies for that.

**Comment by rexroof** [comment]
no worries, as long as I can use the test events to generate all the json that I'd expect to come, I'm a-okay.

**Comment by rexroof** [comment]
I want to comment, because I'm not sure if it was obvious:
the messages that I posted in my original opening of this issue were BOTH events that came from tau, it's just that one was a test event and the other was actually triggered by a real event from twitch.   the REAL event does contain a "months" attribute.  could that be replacing streak_months?

so if the new format always puts the response under a data attribute, does that mean all of the test events should match the real events coming from twitch?
seems like that would mean that I don't have to change my code if it's just designed with the existing test events?
