### ISSUE TITLE
Lock docker image versions

### ISSUE THREAD

**Issue by wwsean08** [FiniteSingularity/tau#41]
To prevent issues and differences between deployments, lock the version of postgres/redis to specific versions.  Currently postgres is using latest, and redis is using the latest alpine image.  This would help with difficult to reproduce issues down the line potentially.

**Comment by FiniteSingularity** [comment]
Good thought.  We're right in the middle of overhauling the docker container setup, see issue #35 . I've added this to the list in that issue.
