### ISSUE TITLE
Move django postgres DB creation out of Postgres container first run, and into app container.

### ISSUE THREAD

**Issue by FiniteSingularity** [FiniteSingularity/tau#46]
Currently, the first time the postgres container is spun up, an init script is run to generate both the Django DB, and the Django DB User.   If there is an error in the .env regarding the Django DB values during initial setup, this necessitates deleting the postgres volume before re-running the install process.

If we move the creation to a script that is run on the django/app container startup (where a script checks to see if the database/user exist, and if they dont, create them using the defined root `POSTGRES_PW`), these sorts of errors during setup are much easier to recover from- simply `docker compose down`, modify the values in the .env file, then `docker compose up`.

**Comment by mtfoley** [comment]
I'd love to take a run at this, if I can.

**Comment by FiniteSingularity** [comment]
Go for it!  I just request we do it in python, to keep things... python.. :D   In fact, the code should probably go in the `wait_for_postgres.py` script.  Add some code to check if the `DJANGO_DB` and `DJANGO_USER` exist.. if not, create them (you'll need to use the POSTGRES_PW and user, which are already assigned at the top of the `wait_for_postgres.py` code.  We could also add code, to update the DJANGO_PW to a new value if it is changed.  That way a user can change their django db PW by updating their .env file.

**Comment by FiniteSingularity** [comment]
I dont know if we're actually calling `wait_for_postgres.py` right now.. but we really should be.. the purpose of that script is to make sure that the postgres container has all started up, and postgres is running properly.

**Comment by mtfoley** [comment]
I don't think it's being called in the current codebase. I tweaked it some and managed to get it running in the last step of Dockerfile, and then had some other things to go do.  I'll have a little reading to do about psycopg2 and hope to have a PR for you this weekend.

**Comment by FiniteSingularity** [comment]
What we should do, is have it run as the first step in the run command, but only if the DJANGO_DB_TYPE=postgres.  So would probably work best to have the wait_for_postgres.py exit if DJANGO_DB_TYPE=sqlite3.

**Comment by mtfoley** [comment]
Yeah I'd been thinking the same, let it make an early exit in the case where it's not equal to Postgres
