### ISSUE TITLE
TAU errors in the dashboard UI upon receiving a cheer 

### ISSUE THREAD

**Issue by brandonroberts** [FiniteSingularity/tau#55]
On a previous livestream, I was receiving events in the UI until I received a cheer. After I received a cheer with some bits, the UI no longer displayed incoming events. I still received messages through the websocket connection though. Screenshots are attached.

![Screenshot from 2021-06-09 11-30-58](https://user-images.githubusercontent.com/42211/121417701-cd4db580-c92f-11eb-9126-cfbddeec829a.png)
![Screenshot from 2021-06-09 11-45-24](https://user-images.githubusercontent.com/42211/121417704-cde64c00-c92f-11eb-8d42-a64a0fff947d.png)

**Comment by FiniteSingularity** [comment]
Thanks Brandon.  It looks like the issue is not in TAU capturing/recording/passing on the event, but rather a bug in the data format of what the dashboard is trying to show.
